openapi: 3.0.1
tags:
  - name: documents
    description: Documentation used in the request.
  - name: priceChart
    description: Chart with list of prices.
info:
  title: TF_Documentation
  description: This API offers methods to generate or recover documents.
  contact:
    name: Flowable
    url: http://www.flowable.com/
  version: 1.0.2
  x-santander-catalogation:
    bian-landscape-version: Unknown
    bian-business-area: Unknown
    bian-business-domain: Unknown
    bian-service-domain: Unknown
  x-pagonxt-catalogation:
    team: Unknown
    domain: Unknown
    system: Unknown
servers:
- url: https://{host}/tf_documentation
  variables:
      host:
        description: The environment where the API is hosted. API Version > 1 must be indicated after basepath (e.g /account-manager/v2)
        enum:
          # CONSUMO INTERNO
          - core.onetrade.dub.dev.api.pagonxt.corp
          - core.onetrade.ams.dev.api.pagonxt.corp
          - core.onetrade.dub.pre.api.pagonxt.corp
          - core.onetrade.ams.pre.api.pagonxt.corp
          - core.onetrade.dub.api.pagonxt.corp
          - core.onetrade.ams.api.pagonxt.corp
        default: core.onetrade.ams.dev.api.pagonxt.corp
security:
  - JWT: []
paths:
  /documents/{document_id}:
    get:
      summary: Find document by id.
      operationId: findDocument
      description: This method allows to find a document.
      tags:
        - documents
      parameters:
        - $ref: '#/components/parameters/header-X-Santander-Client-Id'
        - $ref: '#/components/parameters/header-X-B3-ParentSpanId'
        - $ref: '#/components/parameters/header-X-B3-Sampled'
        - $ref: '#/components/parameters/header-X-B3-SpanId'
        - $ref: '#/components/parameters/header-X-B3-TraceId'
        - $ref: '#/components/parameters/documentId'
      responses:
        '200':
          $ref: '#/components/responses/documentSuccess'
        '204':
          $ref: '#/components/responses/noDataResponse'
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '414':
          $ref: '#/components/responses/error414'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'
        '504':
          $ref: '#/components/responses/error504'
        default:
          $ref: '#/components/responses/errorDefault'
  /prices-charts/export-collection:
    get:
      summary: Generate export collection price chart pdf
      operationId: generateExportCollectionPricesChartPdf
      description: This method allows to generate a chart with a list of prices for an export collection.
      tags:
        - priceChart
      parameters:
        - $ref: '#/components/parameters/header-X-Santander-Client-Id'
        - $ref: '#/components/parameters/header-X-B3-ParentSpanId'
        - $ref: '#/components/parameters/header-X-B3-Sampled'
        - $ref: '#/components/parameters/header-X-B3-SpanId'
        - $ref: '#/components/parameters/header-X-B3-TraceId'
        - $ref: '#/components/parameters/exportCollectionId'
      responses:
        '200':
          $ref: '#/components/responses/priceChartSuccess'
        '204':
          $ref: '#/components/responses/noDataResponse'
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '414':
          $ref: '#/components/responses/error414'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'
        '504':
          $ref: '#/components/responses/error504'
        default:
          $ref: '#/components/responses/errorDefault'
  /prices-charts/import-collection:
    get:
      summary: Generate import collection price chart pdf
      operationId: generateImportCollectionPricesChartPdf
      description: This method allows to generate a chart with a list of prices for an import collection.
      tags:
        - priceChart
      parameters:
        - $ref: '#/components/parameters/header-X-Santander-Client-Id'
        - $ref: '#/components/parameters/header-X-B3-ParentSpanId'
        - $ref: '#/components/parameters/header-X-B3-Sampled'
        - $ref: '#/components/parameters/header-X-B3-SpanId'
        - $ref: '#/components/parameters/header-X-B3-TraceId'
        - $ref: '#/components/parameters/importCollectionId'
      responses:
        '200':
          $ref: '#/components/responses/priceChartSuccess'
        '204':
          $ref: '#/components/responses/noDataResponse'
        '400':
          $ref: '#/components/responses/error400'
        '401':
          $ref: '#/components/responses/error401'
        '403':
          $ref: '#/components/responses/error403'
        '404':
          $ref: '#/components/responses/error404'
        '405':
          $ref: '#/components/responses/error405'
        '406':
          $ref: '#/components/responses/error406'
        '414':
          $ref: '#/components/responses/error414'
        '422':
          $ref: '#/components/responses/error422'
        '429':
          $ref: '#/components/responses/error429'
        '500':
          $ref: '#/components/responses/error500'
        '503':
          $ref: '#/components/responses/error503'
        '504':
          $ref: '#/components/responses/error504'
        default:
          $ref: '#/components/responses/errorDefault'
components:
  schemas:
    StreamingResponseBody:
      type: object
      additionalProperties: false
    Error:
      type: object
      description: Data structure containing the error details
      additionalProperties: false
      properties:
        code:
          type: string
          description: Unique alphanumeric human readable error code
          example: XXX
          pattern: '^[a-zA-Z_0-9 ]*$'
          maxLength: 25
          minLength: 1
        message:
          type: string
          description: Brief summary of the reported issue
          example: Message
          pattern: '^[a-zA-Z0-9. /_-]*$'
          maxLength: 255
          minLength: 1
        level:
          type: string
          description: |-
            Level of the reported issue.
            The possible values are.
            - ERROR
            - FATAL
            - INFO
            - WARNING
          enum:
            - ERROR
            - FATAL
            - INFO
            - WARNING
          example: ERROR
        description:
          type: string
          description: Detailed description of the reported issue
          example: Description
          pattern: '^[a-zA-Z0-9. /_-]*$'
          maxLength: 255
          minLength: 1
      required:
        - code
        - message
        - level
        - description
    Errors:
      type: object
      description: Data structure containing the details for errors
      properties:
        errors:
          type: array
          description: Array of errors
          items:
            $ref: '#/components/schemas/Error'
          maxItems: 50
          minItems: 0
      required:
        - errors
      additionalProperties: false
  parameters:
    header-X-B3-ParentSpanId:
      name: x-b3-parentspanid
      in: header
      description: Position of the parent operation in the trace tree. The value is 64 bits long. The value is omitted when the span is the root of the trace tree.
      example: '0020000000000001'
      schema:
        type: string
        maxLength: 32
        minLength: 0
        pattern: '^[a-zA-Z0-9_]*$'
    header-X-B3-Sampled:
      name: x-b3-sampled
      in: header
      description: |-
        Sampling decision. Sampling is a mechanism to reduce the volume of data in the tracing system.
        In B3, sampling applies consistently per-trace: once the sampling decision is made,
        the same value must be consistently sent downstream. This means that either all or no spans share a trace ID.
        The possible values are:
        - 0 = Deny
        - 1 = Accept
      example: '1'
      schema:
        type: string
        maxLength: 32
        minLength: 0
        pattern: '^[a-zA-Z0-9_]*$'
    header-X-B3-SpanId:
      name: x-b3-spanid
      in: header
      description: 'Position of the current operation in the trace tree. The value is 64 bits long. Do not interpret the value: it may or may not be derived from the value of the TraceId.'
      example: a2fb4a1d1a96d312
      schema:
        type: string
        maxLength: 32
        minLength: 0
        pattern: '^[a-zA-Z0-9_]*$'
    header-X-B3-TraceId:
      name: x-b3-traceid
      in: header
      description: 'Overall ID of the trace, shared by every span in the trace. The value is 64 or 128 bits long.'
      example: 463ac35c9f6413ad48485a3953bb6124
      schema:
        type: string
        maxLength: 32
        minLength: 0
        pattern: '^[a-zA-Z0-9_]*$'
    header-X-Santander-Client-Id:
      name: x-santander-client-id
      required: true
      in: header
      description: Client ID header
      example: a1b30a84-7bf3-442e-84a0-e935d8163b5a
      schema:
        type: string
        maxLength: 36
        minLength: 36
        pattern: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}'
    documentId:
      in: path
      name: document_id
      description: Document id.
      required: true
      schema:
        type: string
        maxLength: 40
        minLength: 40
        pattern: '^CON-[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$'
      example: CON-a1be5ed7-7091-11ed-b775-967337bea149
    exportCollectionId:
      in: query
      name: export_collection_id
      description: Export collection id.
      required: true
      schema:
        type: string
        pattern: '^[A-Z0-9-]*$'
        minLength: 5
        maxLength: 50
      example: CLE-12
    importCollectionId:
      in: query
      name: import_collection_id
      description: Import collection id.
      required: true
      schema:
        type: string
        pattern: '^[A-Z0-9-]*$'
        minLength: 5
        maxLength: 50
      example: CLI-12
  responses:
    documentSuccess:
      description: Expected response to a valid request
      content:
        application/pdf:
          schema:
            type: string
            format: base64
        image/jpeg:
          schema:
            type: string
            format: base64
        image/png:
          schema:
            type: string
            format: base64
    priceChartSuccess:
      description: Expected response to a valid request
      content:
        application/pdf:
          schema:
            type: string
            format: base64
    noDataResponse:
      description: No content response
    error400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err400Example:
              $ref: '#/components/examples/err400Example'
    error401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err401Example:
              $ref: '#/components/examples/err401Example'
    error403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err403Example:
              $ref: '#/components/examples/err403Example'
    error404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err404Example:
              $ref: '#/components/examples/err404Example'
    error405:
      description: Method Not Allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err405Example:
              $ref: '#/components/examples/err405Example'
    error406:
      description: Not Acceptable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err406Example:
              $ref: '#/components/examples/err406Example'
    error414:
      description: URI Too Long
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err414Example:
              $ref: '#/components/examples/err414Example'
    error422:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err422Example:
              $ref: '#/components/examples/err422Example'
    error429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err429Example:
              $ref: '#/components/examples/err429Example'
    error500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err500Example:
              $ref: '#/components/examples/err500Example'
    error503:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err503Example:
              $ref: '#/components/examples/err503Example'
    error504:
      description: Gateway timeout
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            err504Example:
              $ref: '#/components/examples/err504Example'
    errorDefault:
      description: Default error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            errDefaultExample:
              $ref: '#/components/examples/errDefaultExample'
  examples:
    errDefaultExample:
      value:
        errors:
          - code: '500'
            level: FATAL
            message: Internal Server Error
            description: Error description
    err400Example:
      value:
        errors:
          - code: '400'
            level: ERROR
            message: Bad Request
            description: Error validating schema
    err401Example:
      value:
        errors:
          - code: '401'
            message: Unauthorized
            level: ERROR
            description: Unauthorized description
    err403Example:
      value:
        errors:
          - code: '403'
            level: ERROR
            message: Forbidden
            description: Forbidden description
    err404Example:
      value:
        errors:
          - code: '404'
            level: ERROR
            message: Not Found
            description: Not Found description
    err405Example:
      value:
        errors:
          - code: '405'
            level: ERROR
            message: Method not allowed
            description: The request method is known by the server but is not supported by the target resource.
    err406Example:
      value:
        errors:
          - code: '406'
            level: ERROR
            message: Not Acceptable
            description: Not Acceptable description
    err414Example:
      value:
        errors:
          - code: '414'
            level: ERROR
            message: URI Too Long
            description: URI Too Long description
    err422Example:
      value:
        errors:
          - code: '422'
            level: ERROR
            message: Unprocessable Entity
            description: Unprocessable Entity description
    err429Example:
      value:
        errors:
          - code: '429'
            level: ERROR
            message: Too Many Requests
            description: Too Many Requests description
    err500Example:
      value:
        errors:
          - code: '500'
            level: FATAL
            message: Internal server error
            description: Internal server error description
    err503Example:
      value:
        errors:
          - code: '503'
            level: ERROR
            message: Service unavailable
            description: Service unavailable error description
    err504Example:
      value:
        errors:
          - code: '504'
            level: ERROR
            message: Gateway timeout
            description: Gateway timeout error description
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT authentication security

